export const categoriaOptions = [
  "Para Alugar",
  "Vitrine dos Sonhos",
  "Realize Essence",
  "Imóveis no Geral",
  "Imóveis na Planta",
  "Casa em Condomínio",
];

export const caracteristicasUnidade = [
  "Ar Condicionado",
  "Aquecimento Solar",
  "Acabamento em Porcelanato",
  "Acabamento em Laminado",
  "Box",
  "Iluminação em LED",
  "Jardim de Inverno",
  "Cerca Elétrica",
  "Canil",
  "Closet",
  "Fogão a Lenha",
  "Horta",
  "Área Externa",
  "Telhado Colonial",
  "Poço Semi Artesiano",
  "Piscina Aquecida",
  "Móveis Planejados",
  "Energia Fotovoltaica",
  "Lareira",
  "Iluminação Planejada",
  "Pé Direito Alto",
  "Acabamento de Luxo",
  "Fechadura Eletrônica",
  "Automação Residencial",
  "Vista Panorâmica",
  "Acessibilidade PCD",
  "Portão Eletrônico",
  "Circuito de Segurança",
  "Sistema de Alarme",
  "Mezanino",
  "Suite Master",
  "Acabamento em Granito",
  "Vidro Temperado",
  "Topografia Plana",
  "Base para 2º Andar",
  "Acabamento em Blindex",
  "Cozinha Integrada",
  "Gás Encanado",
  "CFTV",
  "Teto Rebaixado em Gesso",
  "Depósito Privativo",
  "Despensa",
  "Sala de TV",
  "Sala de Jantar",
  "Banheira / Hidromassagem",
  "Aquecedor a Gás",
  "Churrasqueira",
  "Varanda Gourmet",
  "Deck",
  "Jardim",
  "Spa",
  "Mirante",
];

export const caracteristicasCondominio = [
  "Playground",
  "Academia",
  "Salão de Festas",
  "Portaria",
  "Portaria 24h",
  "Segurança Interna",
  "Quadra Esportiva",
  "Brinquedoteca",
  "Piscina Coletiva",
  "Sauna",
  "Sala de Jogos",
  "Coworking",
  "Espaço Pet",
  "Bicicletário",
  "Lavanderia Coletiva",
  "Espaço Cinema",
  "Horta Comunitária",
  "Mini Mercado",
  "Gerador de Energia",
  "Vagas para Visitantes",
];