/* ============================================================
   MOCKS DE ENDEREÇO
============================================================ */
export const ESTADOS = [
  { sigla: "MG", nome: "Minas Gerais" }
];

export const CIDADES_POR_ESTADO = {
  MG: [
    "Barbacena",
    "Barroso",
    "Bom Sucesso",
    "Capela Nova",
    "Carandaí",
    "Cipotânea",
    "Conceição da Barra de Minas",
    "Coronel Xavier Chaves",
    "Desterro do Melo",
    "Dores de Campos",
    "Entre Rios de Minas",
    "Ibertioga",
    "Lagoa Dourada",
    "Madre de Deus de Minas",
    "Nazareno",
    "Piedade do Rio Grande",
    "Prados",
    "Resende Costa",
    "Ressaquinha",
    "Santa Bárbara do Tugúrio",
    "Santa Cruz de Minas",
    "Santa Rita de Ibitipoca",
    "Santana do Garambéu",
    "Santos Dumont",
    "São João Del Rei",
    "São Tiago",
    "São Vicente de Minas",
    "Tiradentes"
  ]
};

export const BAIRROS_POR_CIDADE = {
  "São João Del Rei": [
    "Água Geral (Tejuco)",
    "Águas Férreas (Tejuco)",
    "Alto das Mercês",
    "Alto do Maquiné (Colônia do Marçal)",
    "Araçá",
    "Área Rural de São João Del Rei",
    "Barro Preto",
    "Bela Vista",
    "Bom Pastor",
    "Bonfim",
    "Caiçaras",
    "Cananéia",
    "Caquende",
    "Centro",
    "Cidade Nova",
    "Cidade Verde",
    "COHAB",
    "Colinas Del Rey",
    "Colônia do Giarola",
    "Colônia do Marçal",
    "Dom Bosco",
    "Fábricas",
    "Guarda-Mor",
    "Jardim América",
    "Jardim Colônia (Colônia do Marçal)",
    "Jardim das Acácias",
    "Jardim Montese",
    "Jardim Paulo Campos",
    "Lava Pés",
    "Lombão",
    "Loteamento do Carmindo (Colônia do Marçal)",
    "Matozinhos",
    "Morro Grande",
    "Nascente do Sol (Colônia do Marçal)",
    "Nossa Senhora da Conceição",
    "Novo Horizonte",
    "Parque Real",
    "Parque São João Del Rei (Colônia do Marçal)",
    "Pio XII",
    "Portal Vila Rica (Colônia do Marçal)",
    "Rainha da Paz",
    "Recreio das Alterosas (Colônia do Marçal)",
    "Residencial Dom Lucas Moreira Neves",
    "Residencial Girassol",
    "Residencial Jardim Aeroporto",
    "Residencial Lenheiro",
    "Residencial Maquiné",
    "Residencial São José Operário (Tejuco)",
    "Rio Acima",
    "Risoleta Neves IF",
    "São Caetano",
    "São Francisco (Colônia do Marçal)",
    "São Geraldo",
    "São José Operário",
    "São Judas Tadeu",
    "São Pedro (Colônia do Marçal)",
    "Segredo",
    "Senhor dos Montes",
    "Solar da Serra (Colônia do Marçal)",
    "Tejuco",
    "Vale Nascente do Sol",
    "Várzea do Faria (Bonfim)",
    "Vila Belizário",
    "Vila Brasil",
    "Vila do Carmo (Colônia do Marçal)",
    "Vila Jardim Nossa Senhora de Fátima",
    "Vila Jardim São José",
    "Vila Jesus Silva",
    "Vila João Lombard (Fábricas)",
    "Vila Marchetti",
    "Vila Maria (Bonfim)",
    "Vila Militar",
    "Vila Santa Terezinha",
    "Vila Santo Antônio (Matozinhos)",
    "Vila São Bento",
    "Vila São Paulo (Fábricas)",
    "Vila São Vicente (Colônia do Marçal)"
  ],

  "Santa Cruz de Minas": ["Centro","Bom Clima", "Rosa Mística", "Cohab", "Porto Real", "Bela vista"],

  "Tiradentes": ["Centro", "Cuiabá", "Bandeirantes 1", "Bandeirantes 2", "Elvas", "Condomínio Alto dos Cuiabás",
  "Condomínio Tiradentes Ville", "Água Santas", "Cesar de Pina", "Mococa", "Alto da Torre",
  "Candonga", "Capote", "Cascalho", "Pacu", "Parque das Abelhas", "Santíssima Trindade", "Varzea"  
  ],

};